default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost 
  port: 5432

development:
  <<: *default
  database: cnab_parser_development

test:
  <<: *default
  database: cnab_parser_test

production:
  primary: &primary_production
    <<: *default
    database: cnab_parser_production
    username: cnab_parser
    password: <%= ENV["CNAB_PARSER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cnab_parser_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cnab_parser_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cnab_parser_production_cable
    migrations_paths: db/cable_migrate
